openapi: 3.0.3
info:
  title: Markdown site
  description: Markdown site用API
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: ユーザー関係
  - name: auth
    description: 認証関係
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      description: ログイン
      operationId: login
      parameters:
        - in: header
          name: X-XSRF-TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/request/loginRequest.yaml"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/response/loginResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "419":
          description: Page Expired
        "500":
          description: Internal Server Error
  /register:
    post:
      tags:
        - user
      summary: ユーザー情報登録
      description: ユーザー情報を新規登録
      operationId: createMe
      parameters:
        - in: header
          name: X-XSRF-TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/request/createMeRequest.yaml"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "./schemas/response/createMeResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "419":
          description: Page Expired
        "500":
          description: Internal Server Error
  /csrf:
    get:
      tags:
        - auth
      summary: csrfトークン取得
      description: csrfトークンを取得
      operationId: getCsrfToken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/response/getCsrfTokenResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
